workflows:
  android-workflow:
    name: Android Debug Build
    environment:
      java: 17
    scripts:
      - name: Generate Gradle Wrapper
        script: gradle wrapper --gradle-version 8.7 --distribution-type all
      - name: Set permissions
        script: chmod +x ./gradlew
      - name: Build Debug APK
        script: ./gradlew assembleDebug --stacktrace
    artifacts:
      - app/build/outputs/apk/debug/*.apk
